Pr/streams
wdmapp/gtensor pull request #145
Opened 2021-11-05 02:23 UTC by bd4

Simple (not space templated) stream implementation for all backends, assign and launch. Does not provide a queue are for async copy yet. Has a couple of unit tests in tests/test_streams.cxx.

Note that the SYCL approach to streams, queue objects, is arguably a better fit for a C++ library. However the main goal with the gtensor streams implementation is to allow interoperability with other libraries that already use stream directly, e.g. StarPU.

2021-11-05 02:24 UTC, bd4 commented
Fixes #138

2021-11-06 14:57 UTC, germasch requested changes
The main thing I think will need to be fixed eventually is that, as far as I can tell, the `stream_wrapper` and `stream_view` types are fixed at compile time by means of ifdefs, but I think that can be improved later.

2021-11-06 14:57 UTC, germasch commented on include/gtensor/backend_host.h
> +};
If no actual streams exist, do we still need `stream_`? Can't this just be an empty class, which always `is_default()`? And I'm not sure whether it needs `get_backend_stream()`, since I'd think that never gets called, since it doesn't return anything usable. So it may not need `get_backend_stream()`, but even if does for some reason, it could just return `nullptr`.

2021-11-06 14:57 UTC, germasch commented on include/gtensor/backend_host.h
> +#endif
Is this ever actually used? In any case, as above, I don't think it really needs the `stream_` member.

2021-11-06 14:57 UTC, germasch commented on include/gtensor/backend_sycl.h
> +    }
If you're checking this, you might as well check whether it's negative, too.

2021-11-06 14:57 UTC, germasch commented on include/gtensor/backend_sycl.h
> +};
I don't know the semantics of sycl queues (are they reference counted somehow?). A view generally shouldn't make a copy, just keep a reference, but maybe the copy here doesn't really have copy semantics?

2021-11-06 14:57 UTC, germasch commented on include/gtensor/gtensor.h
> +  detail::launch<N, S>::run(shape, std::forward<F>(f), stream);
Isn't it possible to avoid the duplication here by make the stream_view argument a default argument?

2021-11-06 14:57 UTC, germasch commented on tests/test_stream.cxx
> +  gt::assign(b, a, stream.get_view());
I'd think it should be possible to have a conversion operator that gives you a view automatically. On a side note, I don't really like `gt::stream_wrapper`. Can't we just call it `gt::stream`?

2021-11-06 18:25 UTC, bd4 commented on include/gtensor/backend_host.h
> +};
I think it just needs the default and void* ctor, will try it.

2021-11-06 18:28 UTC, bd4 commented on include/gtensor/backend_host.h
> +#endif
Allows the tests to run on host, which exercises some bits of code that wouldn't otherwise be. But I don't have a strong opinion about it - it is an odd dummy class. I could ifdef GTENSOR_HAVE_DEVICE for the tests instead.

2021-11-06 18:29 UTC, bd4 commented on include/gtensor/backend_sycl.h
> +};
SYCL objects like queues  have reference semantics - copies behave the same as the original and it keeps a reference count. I believe this makes it more idiomatic to just use copies, rather than adding another layer of reference semantics on an already reference semantic construction. But I'm not sure, still wrapping my head around it. I did use reference in my earlier SYCL backend code before I understood this.

2021-11-06 18:31 UTC, bd4 commented on include/gtensor/gtensor.h
> +  detail::launch<N, S>::run(shape, std::forward<F>(f), stream);
I spent several hours trying to get this to work and didn't succeed - I don't think it's worth the complexity. I also tried with a simple example in compiler explorer and ran into similar problems - default args only work nicely with templated types in the simplest case.

2021-11-06 18:31 UTC, bd4 commented on tests/test_stream.cxx
> +  gt::assign(b, a, stream.get_view());
Sure, `gt::stream` does sound better.

2021-11-06 19:02 UTC, germasch commented on include/gtensor/backend_host.h
> +#endif
Well, I'm not particularly opposed to having it, but since it's not actually doing anything, I don't think it needs to have `stream_` member which looks like it could have actually meaningful values, if it really doesn't, so this is mostly about keeping these two as simple as possible.

[I'm on the other hand not entirely convinced that it's a good idea to pretend that we can create streams on the host if we really don't, but I don't have a particularly strong opinion on that right now].

2021-11-06 19:03 UTC, germasch commented on include/gtensor/backend_host.h
> +};
Does it really need the `void *` ctor if it always gets passed nullptr? (Or does it not?)

2021-11-06 19:03 UTC, germasch commented on include/gtensor/backend_sycl.h
> +};
That's fine -- if it already is ref counted, why not take advantage of it.

2021-11-06 19:04 UTC, germasch commented on include/gtensor/gtensor.h
> +  detail::launch<N, S>::run(shape, std::forward<F>(f), stream);
But currently the `stream_view` isn't actually a template, or is it?

2021-11-06 19:09 UTC, bd4 commented on include/gtensor/gtensor.h
> +  detail::launch<N, S>::run(shape, std::forward<F>(f), stream);
True, it will likely work now that I dropped the template arg. But is it worth changing now to use default args when we likely want to templatize in the next revision? I want to have Carlos actually use this first and than can iterate.

2021-11-06 19:41 UTC, bd4 commented
I think this is ready now. I can be persuaded to change to use default args if you feel strongly about it, but as I said this will likely need to change again if it becomes templated again.

2021-11-07 02:12 UTC, germasch commented
The update looks good. I don't think there should be a problem with default args even when using templates (see slack), so I'd prefer to not have the duplication, but it can also be fixed later. It does look like you need to rebase the whole thing on top of latest `main`, though.

2021-11-08 14:17 UTC, germasch approved these changes

2021-11-08 14:17 UTC, germasch commented on include/gtensor/gtensor.h
> +                        gt::stream_view stream = gt::stream_view{})
Not worth changing, but fwiw:

```
gt::stream_view stream = {}
```

should work as well and removes some redundancy.

2021-11-08 19:15 UTC, bd4 commented
rebased

2021-11-08 19:35 UTC, merged