Pr/test gene 6d
wdmapp/gtensor pull request #177
Opened 2022-05-13 00:25 UTC by bd4

Add tests for non-contiguous view assignment, and attempt to improve error handling on dimension mismatch. This is to aid in debugging the 0x2b errors on crusher.

2022-05-14 00:22 UTC, germasch requested changes
LGTM except one minor nitpick.

2022-05-14 00:22 UTC, germasch commented on include/gtensor/gfunction.h
> +
Is this the standard C header? If so, it should be included via `#include <assert.h>`, or really, via `#include <cassert>`. I think/hope it's not a header included with gtensor, since that'd obviously be confusing.

2022-05-14 00:22 UTC, germasch commented on include/gtensor/gtensor_span.h
> +#include <assert.h>
Well, I guess there must have been a reason to change from `cassert` (cuda device code?). Nevertheless, the one mentioned above should use angled brackets.

2022-05-16 18:17 UTC, bd4 commented on include/gtensor/gtensor_span.h
> +#include <assert.h>
Device side assert was not working, even when NDEBUG is not set. I imagine cassert includes assert.h eventually, so I don't think it should make a difference... and appears not to have. I guess I will change it back. I still don't understand why device side assert is doing nothing.

2022-05-16 21:18 UTC, bd4 commented
I think the shape check was disabled before we had the scalar specific assign specialization. I am going to test this branch with GENE, and make sure it works there; it does pass the unit tests.

2022-05-31 22:57 UTC, bd4 commented
@germasch the assert issue is fixed now

2022-06-02 16:04 UTC, germasch approved these changes

2022-06-02 16:23 UTC, merged