Pr/blas getri
wdmapp/gtensor pull request #188
Opened 2022-07-21 19:51 UTC by bd4

Adds `gt::blas::getri_batched`, along with tests and benchmark, and refactors and improves stream handling. 

* refactor stream handling in gt-blas, using stream_view for set/get instead of gt::blas::stream_t
* bandsolver family of calls now take a blas handle, and respect the stream set on the handle
* reduction API now has an optional stream_view argument.
* C API still uses gt::blas::stream_t, to keep disruption to existing Fortran code to a minimum.

2022-07-24 13:50 UTC, germasch requested changes
Looks good to me with some minor comments.

It does generally somewhat bother me, though, that there is this rather huge amount of code for something that doesn't seem like it should be that complex...

2022-07-24 13:50 UTC, germasch commented on benchmarks/bench_getri.cxx
> +
FWIW, I think we do have code that allows `std::cout << M` etc. If that doesn't work / isn't helpful, it may be worth looking at fixing it. (Also, it might be useful to have something that dumps an xtensor into, e.g., a numpy-format file)

2022-07-24 13:50 UTC, germasch commented on include/gt-blas/bandsolver.h
> +                                   int ldc, int batchSize)
Why is `h` passed as a pointer? I earlier got the impression that handles themselves are easily copied (preserving reference semantics, since usually the internal of a handle is just a pointer, anyway).

Even if there is a reason to avoid a copy, I'd think passing the handle by reference would be preferred over the explicit pointer. That is, unless `h` could be `nullptr`, but I don't think that's the case here.

2022-07-24 13:50 UTC, germasch commented on src/cgtblas.cxx
>  }
Is there a reason to not have this function return its result instead? (This is a question about pre-existing behavior)

2022-07-24 13:50 UTC, germasch commented on tests/test_lapack.cxx
> +  expect_complex_near(h_C(2, 2, 1), T(0.036, 0.052));
Not really important, but in cases like this, wouldn't it be possible to define a reference solution and than do something like `expect_near(h_C, ref_C);`?

2022-07-24 19:17 UTC, bd4 commented on include/gt-blas/bandsolver.h
> +                                   int ldc, int batchSize)
The only advantage I see of a pointer is that it allows more flexibility with Fortran interop and flexible scope. We are not using that now though - the C lib uses a global handle and the handle never makes it into Fortran land. I'm not opposed to changing it to use reference.

2022-07-24 19:19 UTC, bd4 commented on src/cgtblas.cxx
>  }
Only reason is less work in changing Fortran interface and call sites. Re original design, it was modeled after cublas, which also involved less changes to the existing Fortran interface call cublas_set_stream etc.

2022-07-24 19:23 UTC, bd4 commented on tests/test_lapack.cxx
> +  expect_complex_near(h_C(2, 2, 1), T(0.036, 0.052));
array near already exists actually - it usually comes down to whether I copy/pasted one of the blas tests from an older test before I wrote that or a newer one. If I do heavy modifications to a test, I usually rewrite it, but other times feels not worth the effort.

2022-07-24 19:56 UTC, germasch commented on include/gt-blas/bandsolver.h
> +                                   int ldc, int batchSize)
This is a templated function, ie., not one which could possibly be called directly from Fortran. I think passing as `handle_t&` would be just fine, if we want to avoid any potential complications about whether a copy of `handle_t` has reference semantics or not. I think the modern C++ is basically to avoid raw pointers wherever possible, and if one has a choice of using reference vs pointer, a reference should be used when it's clear that there's always an object present, as opposed to a pointer, which would be used if `nullptr` is an expected (and handled) choice.

2022-07-24 19:58 UTC, germasch commented on src/cgtblas.cxx
>  }
It's not something that needs to be changed (as I said, it's not something which was changed in this PR). But generally speaking, I think in C++ in particular it is preferable to return things that should be returned (in particular given return value optimization etc it's usually not more expensive, and there's pair/tuple etc for multiple values). And I would agree that having two different function signatures for C++ vs C wrappers isn't necessarily making life easier.

2022-07-25 14:09 UTC, bd4 commented on include/gt-blas/bandsolver.h
> +                                   int ldc, int batchSize)
I think handle_t should also be a class that manages the underlying e.g. cublasHandle_t (calling create and destroy as needed). Then the instances can still be passed by reference, and if non lexical scope is really needed, caller can use unique_ptr. Fortran interface can still be whatever.

2022-07-25 17:50 UTC, bd4 commented
> Looks good to me with some minor comments.
> 
> It does generally somewhat bother me, though, that there is this rather huge amount of code for something that doesn't seem like it should be that complex...

Wrapping APIs with slight differences (or in the case of oneMKL, significant differences) is a mess. I tried to use templates and in some case C preprocessor to make it less bad, but only so much one can do without going down the path of code generation, and I would argue that adds new problems and isn't worth it for this. There are efforts in C++ standardization for linear algebra, hopefully that eventually leads to something that makes the situation better.

2022-07-25 18:34 UTC, germasch approved these changes
LGTM!

2022-07-25 19:21 UTC, merged