indexing: use size_type for flat index and kernel
wdmapp/gtensor pull request #192
Opened 2022-08-05 17:00 UTC by bd4

Does not change external interface (shape_type is still int sarray).
This should make sure there is no int overflow in internal index
calculations. Note that reshape could still overflow, but the
assert that the sizes stayed the same in the implementation should
at least catch it in debug builds.

2022-08-05 17:06 UTC, bd4 commented
Note that using size_type for index calculations could have performance impact.

2022-08-05 18:47 UTC, germasch requested changes

2022-08-05 18:47 UTC, germasch commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
I guess I'm not totally convinced of this, since likely current hardware doesn't support a configuration with that many threads, ie., it cannot possibly happen. Also, in particular in this case, since that index is then passed to `operator()`, it'd be truncated at that point, but that then can also not happen.

In the end, I don't particularly mind this, but it's something to be revisited. In particular, it'd probably be smart to not launch 100 million threads for an array of size 100 million anyway, but rather launch something more reasonable and then have a loop that catches all indices, I think that generally is also better for performance.

2022-08-05 18:47 UTC, germasch commented on include/gtensor/assign.h
> +  size_type j = threadIdx.y + blockIdx.y * BS_Y;
I'm at this point not sure whether you're changing `operator(int{, int, ...)`, but I don't think we should. So since i and j are used for that, we shouldn't pretend they could be that large (and at some point one really might take a performance hit from doing more 64 bit calcs/registers than necessary).

2022-08-05 18:47 UTC, germasch commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
This one I have less concerns about, since the result gets passed to unravel, which takes a size type.

I guess the other comment on all of these is that they look like they may support a > 32 bit space, but they're not actually correct for that, since the r.h.s. will still be calculated in uint32_t (and possibly overflow), only the result is then extended to 64 bit.

2022-08-05 18:47 UTC, germasch commented on include/gtensor/assign.h
> +        size_type j = item.get_id(0);
Again, if operator() still takes int and not size_type, this makes it look like we support something we don't, and possibly makes it more expensive. I suppose `auto` would be just fine here.

2022-08-05 18:47 UTC, germasch commented on include/gtensor/assign.h
> +  for (size_type i = 0; i < lhs_shape.size(); i++) {
👍

2022-08-05 18:47 UTC, germasch commented on include/gtensor/gtensor.h
> +  size_type k = b;
These calculations are likely expensive as-is already, and extending them to 64 bit for no benefit doesn't seem worth it -- these are basically hardware-specific sections of the code which I think are ok to be tuned to the particular hardware capabilities (but comments about it wouldn't hurt).

2022-08-05 18:47 UTC, germasch commented on include/gtensor/gtensor_storage.h
> +  for (size_type i = 0; i < h1.size(); i++) {
👍

2022-08-05 21:44 UTC, bd4 commented on include/gtensor/assign.h
> +  size_type j = threadIdx.y + blockIdx.y * BS_Y;
`operator()` is actually templated, so will use whatever type it's passed. I think that this approach is too heavy handed in any case - my thinking now is that we should have size_type and / or index_t which are used consistently and can be configured with defines - that seems like the header-only library way of doing things.

2022-08-05 21:46 UTC, bd4 commented on include/gtensor/assign.h
> +        size_type j = item.get_id(0);
operator takes whatever you give it, if I am reading the code correctly. So I think use size_type for sycl makes sense. And actually yes, `auto` would be better, we just inherit what sycl uses then.

2022-08-05 21:47 UTC, bd4 commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
I am inclined to use size_type at least for the nd implementations, because it's already using unravel. but it could still have performance impact...

2022-08-05 21:52 UTC, bd4 commented
Related - I think using size_type for the dimension is overkill, but I don't know that it makes any difference, e.g. with compile time. SYCL uses int for dimensions, which surprises me a little, why not unsigned int?

2022-08-05 22:53 UTC, bd4 commented
I think the first commit should be uncontroversial now. The other two are a step towards making it so we have more control over the index_type, but is maybe still not fully baked...

2022-08-05 22:55 UTC, bd4 commented
Related to #191

2022-08-06 00:10 UTC, germasch commented on include/gtensor/assign.h
> +  size_type j = threadIdx.y + blockIdx.y * BS_Y;
I think it's probably too difficult to try to have distinct index_t, size_t and still get something consistent. E.g., if one flattens an array, one would expect `x_flat(i)` to be the same as `x.data()[i]`. So I think it'd be easier to say "we're using all 32-bit" vs "all 64-bit" and not try to be smart, as I was kinda trying to be. In addition, I still think in particular gpus may benefit from index computations never involving 64 bit.
The other part to this is what to do about signedness, though I guess one way is to just keep `operator()` templated and essentially leave it to the user. I can't quite wrap around my head of where signed values actually make sense, definitely not for regular accesses. xtensor has `.periodic(i, ...)`, where negative indices are meaningful, but I don't think we have that yet at all. For slices, negative indices are meaningful as well, but that should have its own distinct type. I guess part of this question is, what are we (ab-)using `shape_type` for?

2022-08-06 17:47 UTC, bd4 commented
Force pushed just the commit changing internal use of size_type when dealing with .size and unravel, which I think is uncontroversial. The size_type v index_type thing is hopefully unnecessary, and needs more discussion

2022-08-06 17:47 UTC, bd4 commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
Removed from this pr pending further discusion

2022-08-06 17:54 UTC, bd4 commented on include/gtensor/assign.h
> +  size_type j = threadIdx.y + blockIdx.y * BS_Y;
We use `shape_type` for strides. I can't think of any place it's used currently where it needs to take a negative value. I am leaning towards uint32_t as default size_type used by shape_type, maybe size_t for SYCL, with ability to change it with cmake options. Can deal with the reverse indexing e.g. in bandsolver as a special case. But needs more discussion, will be a separate PR when we decide.

2022-08-06 19:43 UTC, germasch requested changes
Looks good with one issue remaining (repeated in two places).

2022-08-06 19:43 UTC, germasch commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
I still don't like this, since the rhs is `uint32_t` anyway. I think it'd be somewhat consistent to make the rhs `uint32_t` as well, or `auto` would work here as well.

2022-08-06 19:43 UTC, germasch commented on include/gtensor/gtensor.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
same as above

2022-08-07 04:00 UTC, germasch commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
I think you may have missed undoing this change to `size_type`, but did push commits from your other PR by mistake?

2022-08-07 17:52 UTC, bd4 commented on include/gtensor/assign.h
> +  size_type i = threadIdx.x + blockIdx.x * blockDim.x;
I left the size_type change in on purpose for the nd kernels, where it's immediately passed to unravel as size_t anyway. I just tested and this alone does not workaround the HIP compiler bug - casting blockIdx.x to size_type does. I think it is worth doing until we do a deeper refactor.

2022-08-07 18:23 UTC, germasch approved these changes
LGTM. I guess I'm not holding my breath for an immediate fix from AMD, so workaround it is.

2022-08-07 19:10 UTC, merged