hip: GTENSOR_DEVICE_HIP_MANAGED_MEMORY_TYPE opt
wdmapp/gtensor pull request #198
Opened 2022-08-14 17:45 UTC by bd4

Set to 'coarse' (default), 'device', or 'fine'. Note that this is
a change to default behavior - previous default was 'fine'.

2022-08-14 22:54 UTC, germasch requested changes
I think macros are useful to be able to set a default without having to change add code into, e.g., GENE. But I think a nicer approach would be some kind of `gt::setManagedMemoryType()` or something that could be called programmatically. That might be useful to actually test/benchmark the various types without having to reconfigure/rebuild the whole thing, but most of all it means that all paths would always be compiled, which I think is one of the main drawbacks of ifdefs.

Again, the default could be chosen by a macro (and in that case, I think one can make a single macro work that takes values like `fine`, `coarse`, etc) Obviously one would have to think about what to do for non-hip backends (probably, ignore, except `device`, which makes sense on cuda, too).

2022-08-15 18:41 UTC, bd4 commented
Re a library global setter, this would need to use the local static var hack to keep global state in header only library. This is what the SYCL backend uses to keep track of the "global" queue objects.

device/managed both make sense for cuda and sycl, at least for machines which have transparent host access to device mem (at the very least this is true for intel integrated gpu, e.g. laptop, and summit for cuda).

GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT = (managed, device, managed_course, managed_fine). On AMD, managed is an alias for managed_coarse if ROCm 5+, otherwise alias for managed_fine. Does that sound reasonable? I didn't realize one could do string compare in macros? Hopefully can drop support for ROCm < 5 in a few months, just need to make sure CI machines use it

2022-08-15 22:14 UTC, bd4 commented
Interestingly, crusher is the only machine so far where transparent access to device memory truly works. Assigning it on Gen9 Intel integrated gpu, and on summit, results in segfault.

2022-08-16 14:53 UTC, germasch requested changes
Still have some nitpicks ;)

2022-08-16 14:53 UTC, germasch commented on include/gtensor/device_backend.h
> +#define GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT ManagedMemoryType::Managed
I think I would skip the namespace/enum in this define, it makes it awkward to use: `-DGTENSOR_MANAGED_MEMORY_TYPE_DEFAULT=Managed` is nicer than `GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT=ManagedMemoryType::Managed`, in particular in the case where someone might not be using cmake to take care of it.

2022-08-16 14:53 UTC, germasch commented on include/gtensor/device_backend.h
> +enum class ManagedMemoryType { Managed, Device, ManagedFine, ManagedCoarse };
Sorry to be nitpicky, but generally gtensor doesn't use camel case, but lower case with underscores, so I think we should stick with that.

2022-08-16 14:53 UTC, germasch commented on include/gtensor/device_backend.h
> +class GtensorConfig
I guess the camel case comments goes for this, too, even though it's not public-facing, so it's less of an issue, but consistency is still nice.

2022-08-16 14:53 UTC, germasch commented on include/gtensor/device_backend.h
> +class GtensorConfig
I also don't see why this needs to be a class with getters/setters. A simple struct would do, right?

2022-08-16 16:31 UTC, bd4 commented on include/gtensor/device_backend.h
> +enum class ManagedMemoryType { Managed, Device, ManagedFine, ManagedCoarse };
The only other enum in current code base is enum Type in gslice.h, which seems to be camel case. I think there is something to be said for using a different convention for enums vs classes. It does use all caps for values, so at least that should be changed.

2022-08-16 16:33 UTC, bd4 commented on include/gtensor/device_backend.h
> +#define GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT ManagedMemoryType::Managed
I think to make this work, I would need to use plain enum and not class enum. C++20 has using enum, but I don't think there is a way to use unqualified class enum before that?

2022-08-16 17:17 UTC, bd4 commented on include/gtensor/device_backend.h
> +#define GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT ManagedMemoryType::Managed
I didn't figure out a way to make this work. The most obvious `managed_memory_type::GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT` does not work.

2022-08-16 19:01 UTC, germasch commented on include/gtensor/device_backend.h
> +#define GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT ManagedMemoryType::Managed
Ok. I'm pretty sure it could be hacked (may require another macro and ##). But it doesn't seem worth it at this point.

2022-08-16 19:01 UTC, germasch approved these changes

2022-08-16 22:06 UTC, bd4 commented on include/gtensor/device_backend.h
> +#define GTENSOR_MANAGED_MEMORY_TYPE_DEFAULT ManagedMemoryType::Managed
found a surprisingly not too ugly solution for this

2022-08-16 22:29 UTC, merged