rfc: add typestr expression method for debugging
wdmapp/gtensor pull request #202
Opened 2022-08-19 20:46 UTC by bd4

Experimental way to add useful debug info, by calling `expr.typestr()`. This is far easier than template meta programming to do this separately, however it has the downside of requiring including string and sstream throughout the code, which I don't like.

2022-08-22 17:24 UTC, bd4 commented
I think it is possible to do this with a free-standing function in a separate header not included by default. The complication is that private members would need to be exposed in some cases.

2022-08-22 17:33 UTC, bd4 commented
Produces strings like this:
```
# owning (data) gtensor of 2 dimensions, element type double, shape (2,2) strides (1,2)
d2<double>{2, 2}{1, 2}
# 1d view of above, with shape (2) and strides (1)
v1(d2<double>{2, 2}{1, 2}){2}{1}
# function adding gscalar 5 as double to a 2d owning gtensor
fn:(5<double> + d2<double>{2, 2}{1, 2})
# function multiplying 5 as int with a 1d view of 2d owning gtensor
fn:(5<int> * v1(d2<double>{2, 2}{1, 2}){2}{1})
# function multiplying 5 as int with a 2d span
fn:(5<int> * s2<double>{2, 2}{1, 2})
# sin of 2d owning gtensor
fn:sin(d2<double>{2, 2}{1, 2})
```

2022-08-22 20:13 UTC, germasch reviewed
This does seem like a useful addition. I don't think I mind it being added into the individual classes, otherwise one basically has to create a shadow hierarchy.

2022-08-22 20:13 UTC, germasch commented on benchmarks/gt-bm.h
> +  char const* p = __PRETTY_FUNCTION__;
I'm confused how this works, besides being a gcc extension only, I think. 

Isn't __PRETTY__FUNCTION__ alway sgoing to be `get_type_function` since that is the enclosing function? I though usually one has to use macros to be able to get the actual function name of interest (e.g., the way `assert` is a macro rather than an actual function).

2022-08-22 20:13 UTC, germasch commented on include/gtensor/backend_common.h
> +
So I kinda don't like that as I'm looking at this, it's a mix of prefetch, the type printing and some benchmark changes, and if one ever has to bisect back to figure out where something broke, this could become an annoyance, too. I'd prefer if you broke this into a separate PRs.

2022-08-23 19:19 UTC, bd4 commented on benchmarks/gt-bm.h
> +  char const* p = __PRETTY_FUNCTION__;
It works with LLVM and gcc, which covers the compilers we are using now. I don't understand exactly how it works, it's a bit of a hack.. but unfortunately there doesn't seem to be a good general truly standards compliant way to get demangled type names

2022-08-23 19:28 UTC, bd4 commented on benchmarks/gt-bm.h
> +  char const* p = __PRETTY_FUNCTION__;
I could add some comments to the hack. __PRETTY_FUNCTION__ looks like this:
```
const char* get_pretty_name() [with T = long unsigned int]
```
for `get_pretty_name<std::size_t>()`

2022-08-23 20:24 UTC, bd4 commented on include/gtensor/backend_common.h
> +
That is separate commit and actually separate PR that has now been merged, I will rebase.

2022-09-19 13:26 UTC, bd4 commented
The free function version of this does not require creating a shadow hiearachy, it can be done using function overloading. The main downside of having it separate is it complicates access to private members which is needed in many cases. One possible way to work around this, is to encapsulate the printer in a class and make it a friend of all the classes. But then potentially have to include all the extra headers anyway.

I'm going to benchmark compiling with different backends, to see if current version slows things down at all. If not, maybe this way is the simplest / best option.

I wonder if `typestr` is a good name for this - it does include shapes/sizes, which is not technically part of the type in the strict C++ since. I can't think of a better name though, `debugstr` seems confusing.

2022-09-19 13:40 UTC, bd4 commented
Does not appear to affect compile times at all.

2022-09-19 23:47 UTC, germasch requested changes
This looks quite useful, but I'd like to see to the test actually test things, not just print them ;)

2022-09-19 23:47 UTC, germasch commented on tests/test_expression.cxx
> +
I'm feeling a little lazy, so I'd prefer to be able to tell from the test what it's supposed to do ;) I'm pretty sure string `EXPECT_EQ()` will take strings ;)

2022-09-20 21:29 UTC, bd4 commented on tests/test_expression.cxx
> +
Not as lazy as when i wrote this test and saw it in the diff and didn't fix it ;). Pushed improved version that actually is a test, and has some comments on the mini-language used.

2022-09-20 21:58 UTC, germasch approved these changes
👍

2022-09-20 22:12 UTC, merged