add cmake options
wdmapp/gtensor pull request #203
Opened 2022-08-23 21:02 UTC by bd4

add GTENSOR_CHECK_BOUNDS, GTENSOR_CHECK_ADDRESS, GTENSOR_SYNC_KERNELS

2022-08-24 13:59 UTC, bd4 commented
I wonder if check address should be on by default - I don't expect to gtensor_span objects to be construted in a loop, and it aids in early detection of some type of errors.

2022-08-24 17:29 UTC, germasch requested changes
Looks great, other than one tiny bit! ;)

2022-08-24 17:29 UTC, germasch commented on CMakeLists.txt
> +option(GTENSOR_ADDRESS_CHECK "Enable per access bounds checking" OFF)
A little copy&paste mistake here ;)

2022-09-01 00:01 UTC, bd4 commented on CMakeLists.txt
> +option(GTENSOR_ADDRESS_CHECK "Enable per access bounds checking" OFF)
Good catch!

2022-09-12 21:06 UTC, germasch approved these changes

2022-09-12 21:16 UTC, merged