Pr/solver
wdmapp/gtensor pull request #213
Opened 2022-10-10 21:51 UTC by bd4

Adds high level solver interface:
```
#include "gt-solver/solver.h"
gt::blas::handle_t h;
gt::solver::GpuSolverInvert<gt::complex<double>> s(h, N, NBATCHES, NRHS, matrix_batches);
s.prepare();
s.solve(rhs, sol);
```

2022-10-11 01:20 UTC, germasch reviewed
Looks nice, but I did come up with a couple of questions ;)

2022-10-11 01:20 UTC, germasch commented on src/gtsolver.cxx
> +    pmatrix = pdata + n * n * i;
You could just use `auto pmatrix = pdata + ...`, right?

2022-10-11 01:20 UTC, germasch commented on src/gtsolver.cxx
> +
Is there a reason that `prepare()` can't just be called in the constructor? That way, the object wouldn't have a "initialized but not yet usable for solve" kind of state, ie., it'd always be ready to solve and one wouldn't need `prepared_`, either, I'd think?

2022-10-11 01:20 UTC, germasch commented on src/gtsolver.cxx
> +
Maybe that's the reason for the separate `prepare`, but I'd still prefer to have that done internally / with private methods. 

The other somewhat related question here is, is it anticipated that the classes are going to be used through a pointer-to-base class, or is the inheritance just because they share some common code? I think in the former case, it might make sense to have an abstract base class, while otherwise one shouldn't actually need virtual functions?

2022-10-11 19:13 UTC, bd4 commented on include/gt-solver/solver.h
> +extern template class GpuSolverDenseSYCL<gt::complex<double>>;
Just the definition in the .cxx seems to be enough, I'll remove the extern declarations.

2022-10-11 19:19 UTC, bd4 commented on src/gtsolver.cxx
> +
Two reasons, one is to be able to benchmark the preparation step, and the other reason is code re-use and sharing. The latter could probably still be accomplished by making prepare a protected method called at the end of the constructor, but there is less flexibility. The idea is the constructor does the allocations and setting up pointer arrays, and prepare does computation, e.g. factor or inversion.

I agree it's ugly having to explicitly call prepare. I'll see if I can get the code re-use I want if it's called at the end of the constructor. Also there isn't that much code, so some duplication is not the worst.

2022-10-11 19:34 UTC, bd4 commented on src/gtsolver.cxx
> +
Potentially both - they all have the same interface and several of the solver implementations can share code. I think having an abstract base class defining the interface is worth it, and passing a pointer to base solver around could be useful.

I do wonder if it's worth trying to share code - figuring out exactly what arrays are used for which and how to share them most effectively is confusing, and while it does make for less duplication, it makes the code harder to follow, and it's not that much code in the end. So just having an abstract base class to define the interface and allow passing implementations around, is maybe a better design.

These are the likely set of initial implementations:
1) standard dense solve, getrf / getrs
2) invert solve - getrf + getri / gemm
3) alternate dense solve for oneMKL - use strides APIs, getrf / getrs, don't need any of the pointer arrays, but needs additional temporaries based for scratch
4) sparse solve - dense getrf nopivot + convert to single CSR / sparse trsv x2

I don't think it's worth adding the naive band solver, it out-performes dense in some cases but on those platforms the invert solve is pretty much always better, gemm_batch seems to have been optimized everywhere

2022-10-11 19:37 UTC, bd4 commented on src/gtsolver.cxx
> +
rather than sharing code via inheritance, they could share code via helper methods, .e.g `init_device_pointer_array(d_pointers, d_data, data_stride, nbatches)`. Most of the meat is in gt-blas calls anyway, the sharing is just tedious array setup stuff.

2022-10-12 21:19 UTC, bd4 commented
Does not yet have a sparse implementation, but that will be more complicated because of the lack of a existing gt-sparse wrappers and the larger differences among sparse APIs. Seems sensible to merge this first as a starting point.

2022-10-13 03:16 UTC, germasch requested changes
Looks nice -- the only thing I'd still like to see is to have `prepare()` not be virtual (unless I missed something).

In terms of the sparse stuff, I agree with holding off. I think it may not be advisable to try to create a blas-like abstraction layer there, anyway, but basically have a `SolverCuSparse` that directly calls cusparse as needed. (Though cuda and hip may be so similar that it may make sense to have one class for both of them).

The other thing I just noticed as I typed the above is the camel case used here, while I believe all of the rest of gtensor does follow the (rather old) lower case + underscore convention. It'd be kinda nicer to stay consistent with that.

2022-10-13 03:16 UTC, germasch commented on src/gtsolver.cxx
> +}
I think one question here is whether to not just do the preparation here directly, though I don't think I have strong feelings about that (it's not particularly complicated, but kinda ugly-ish with those blas interfaces, so having separate does help a little in terms of keeping things compartmentalized.

However, for what I've seen so far, I don't think `prepare` needs to be virtual, and in fact since you're calling it from the constructor, it will not truly be virtual in any case. (I'd argue it's also not required for every subclass of `Solver` to necessarily have a `prepare` function, it might not really be needed in some cases, e.g., when one has an iterative solver that doesn't need any kind of factorization).

2022-10-13 03:16 UTC, germasch commented on src/gtsolver.cxx
> +  // Note: synchronize so it's safe to garbage collect scratch
I don't think C++ does garbage collection ;) (I do agree that the sync is needed).

2022-10-13 03:16 UTC, germasch commented on tests/test_solver.cxx
> +               gt::raw_pointer_cast(d_C.data()));
off-topic, but all those pointer_cast I've been seeing here and elsewhere lately really makes me think we should seriously consider just using raw pointers throughout.

2022-10-13 03:16 UTC, germasch commented on tests/test_solver.cxx
> +  h_C_expected(4) = 2.5;
I'd still prefer to write this more compactly like `h_C_expected{2.5, 4.0, 4.5, 4.0, 2.5}`, though not sure whether in practice there might be issues with conversion to complex, etc.

2022-10-13 14:59 UTC, bd4 commented on src/gtsolver.cxx
> +
I removed prepare and just moved it into the ctors.

2022-10-13 15:01 UTC, bd4 commented on src/gtsolver.cxx
> +}
I moved it in to the constructors, I think it wasn't serving any real purpose for re-use, and for benchmarking I can always bench the constructor. I don't love that the constructor ends up being so expensive, but still seems like the best design for this, rather than having a extra step.

2022-10-13 15:02 UTC, bd4 commented on src/gtsolver.cxx
> +  // Note: synchronize so it's safe to garbage collect scratch
Even though I haven't used Java in years, it has definitely left it's mark when I do OO programming :P. Fixed in latest commit.

2022-10-13 15:04 UTC, bd4 commented on tests/test_solver.cxx
> +               gt::raw_pointer_cast(d_C.data()));
It is used for `gt::copy_n` to determine which enum to pass to low level cudaMemcpy or similar. Another possibility would be to make the gt-(blas,solver,etc) APIs able to take non-raw pointers, and just remove the layer at the end before calling the low level API. I think raw_pointer_cast just returns arg if already raw, or could be made to.

2022-10-13 15:05 UTC, bd4 commented on tests/test_solver.cxx
> +  h_C_expected(4) = 2.5;
ya I've been meaning to try to debug that, it is annoying having to be so verbose.

2022-10-13 20:48 UTC, germasch commented on tests/test_solver.cxx
> +               gt::raw_pointer_cast(d_C.data()));
Good point, there's definitely stuff that'd break if used untagged pointers. So that might well not be a win, but definitely not easy. So I'm giving up on the thought for now... ;)

2022-10-13 20:49 UTC, germasch approved these changes
👍

2022-10-13 20:55 UTC, merged