7d
wdmapp/gtensor pull request #289
Opened 2024-08-31 14:00 UTC by gmerlo

add support for 7d launch

2024-08-31 14:32 UTC, gmerlo commented
One check fails because the cmake version is too old, the sycl one fails in the test but I don't know where to see the logs (if any) to see what happened. I don't have a sycl platform to test, so I may have easily missed something

2024-08-31 19:46 UTC, bd4 requested changes
Can you add a 7d assign test?

I am looking into the sycl and cmake failures, starting with forcing a CI run on current master branch in case it is not caused by this pr at all.

2024-08-31 19:46 UTC, bd4 commented on include/gtensor/assign.h
> +    int n = tidz % lhs.shape(5) / lhs.shape(4), int o = tidz / lhs.shape(5);
Should be semicolon and new line instead of comma.

2024-09-17 15:17 UTC, bd4 requested changes

2024-09-17 15:17 UTC, bd4 commented on tests/test_launch.cxx
> +              for (int o = 0; n < h_a.shape(6); o++) {
```suggestion
              for (int o = 0; o < h_a.shape(6); o++) {
```

2024-09-17 22:22 UTC, bd4 approved these changes

2024-09-18 00:53 UTC, merged