Pr rocm6
wdmapp/gtensor pull request #290
Opened 2024-09-16 16:00 UTC by gmerlo

Minor fixes necessary for rocm>6

2024-09-17 14:08 UTC, germasch approved these changes
LGTM.

I'm not much of a fan of the `static_cast<void>`, but I suppose you got warnings (or worse) because of the ignored return value -- did you consider actually checking the return value? I usually just do something like

```
rc = hipFree(...);
assert(rc == 0) // or whatever the success return is....
```
Of course, this doesn't actually handle failure either...

2024-09-17 14:25 UTC, bd4 requested changes

2024-09-17 14:25 UTC, bd4 commented on src/fortran/gpu_api.cxx
> -  hipDeviceReset();
This should probably be gtCheck, we don't really want to ingore the return value.

2024-09-17 14:25 UTC, bd4 commented on include/gtensor/backend_hip.h
> +      static_cast<void>(hipGetLastError()); // clear the error
Here we are purposely ignoring the return val to clear the error. I think C style (void) is easier to read, but don't have a strong opinion.

2024-09-17 14:25 UTC, bd4 commented on include/gt-solver/backend/hip-csrsm2.h
> +#include <rocsparse/rocsparse.h>
does this still work with Rocm 5.x? I think we can drop support for 4.x now, but not sure we want to drop 5 yet.

2024-09-17 14:26 UTC, bd4 commented
CI failure is unrelated, I guess we were pulling dev branch of umpire and it wants newer cmake.

2024-09-17 18:38 UTC, gmerlo commented
this was me mostly being lazy and avoiding warnings. There is however a major regression with rocm6, as if the memory is not correctly allocated anymore. But could also be something else, not sure yet what is going so I'll keep this a draft for a little longer

2024-09-20 19:30 UTC, bd4 commented
merged same feature with backwards compat for <5.5 in #292

2024-09-20 19:30 UTC, closed without merging