Clearer error message and HIP architectures
wdmapp/gtensor pull request #293
Opened 2024-12-20 13:57 UTC by td-mpcdf

- In the `macros.h` file, the error message is added to the error code.
- We use the `CMAKE_HIP_ARCHITECTURES` variable to set the hip architecture for AMD GPUs.

2024-12-20 14:14 UTC, germasch requested changes
Looks good, but I have some minor nit picks ;)

2024-12-20 14:14 UTC, germasch commented on CMakeLists.txt
> +  #    CACHE STRING "GPU targets to compile for")
Could you just remove these two lines? I guess it looks like `GPU_TARGETS` isn't being used at all currently, right?

2024-12-20 14:14 UTC, germasch commented on include/gtensor/macros.h
> +    fprintf(stderr, "(%s)\n", hipGetErrorString(last_error));
Looks good, except that `clang-format` complains, so please update the formatting.

2025-04-07 13:33 UTC, td-mpcdf commented on include/gtensor/macros.h
> +    fprintf(stderr, "(%s)\n", hipGetErrorString(last_error));
OK, thanks for reviewing. I changed the files accordingly.

2025-04-07 16:06 UTC, merged