Pr/device management
wdmapp/gtensor pull request #36
Opened 2020-09-21 20:32 UTC by bd4

2020-09-21 20:53 UTC, bd4 commented
I think a the cuda kernels in GENE will work in HIP just by changing the special launch syntax to use gtLaunchKernel. This is actually already present since gtensor.h includes device_backend.h which includes macros.h. I'm thinking gtensor/capi.h should also include macros.h, I think it's all C safe now.

2020-09-21 20:57 UTC, bd4 commented
Using them is a hack since they won't work with SYCL. But sometimes doing a hack first makes sense... gives us some time as the SYCL implementations mature, and for GENE branches that already have gtensor ports of kernels to be merged.

2020-09-22 01:08 UTC, germasch requested changes
Looks pretty good, but I do have a couple of comments.

2020-09-22 01:08 UTC, germasch commented on include/gtensor/device_backend.h
> +  static T* allocate(int count)
This should probably be `size_t` rather than `int`. My general take on this is that if one allocates a m x n x l array, it's usually okay for the individual dims to be `int` (though one can definitely argue about that, too). But allocating something > 4GB (or 4e9 x sizeof(float)) is something that can actually happen.

2020-09-22 01:08 UTC, germasch commented on include/gtensor/device_backend.h
> +  {
And so while this is `size_t`, I think it should be the same type used above, because I also think it should be a count, rather than bytes. Since this is templated by `T`, I think the API should be consistently in terms of count of elements.

2020-09-22 01:08 UTC, germasch commented on src/cgtensor.cxx
> +extern "C" int gt_backend_device_get_count()
I think if you declare the function `extern "C"` in the header, you don't have to repeat that here.

2020-09-22 01:08 UTC, germasch commented on include/gtensor/capi.h
> +extern "C" void gt_synchronize();
I think you'll find that you can't include this from C, since C doesn't understand `extern "C"` ;)

I like going the `{BEGIN.END}_C_DECLS` (macros) way.

2020-09-22 01:08 UTC, germasch commented on include/gtensor/device_backend.h
> +  static void copy(const T* src, T* dst, std::size_t count)
When the arg is called `count`, it's yet more misleading. I haven't looked at the existing allocators, but I'd argue the same there, if their interface is like this, too.

2020-09-22 01:38 UTC, bd4 commented on include/gtensor/device_backend.h
> +  static T* allocate(int count)
ok using gt::size_type everywhere. It's actually all counts, I missed one of the 'bytes' names when I made the change and then copied it when I made the managed allocator.

2020-09-22 01:38 UTC, bd4 commented on include/gtensor/device_backend.h
> +  static void copy(const T* src, T* dst, std::size_t count)
it is truly a count (number of T's)

2020-09-22 02:21 UTC, germasch commented on include/gtensor/device_backend.h
> +  static T* allocate(int count)
In the C routines for Fortran interfacing, you should use a standard `size_t` (a.k.a. `C_SIZE_T` from Fortran) to avoid potential trouble there.

2020-09-22 02:22 UTC, germasch commented
github says the branch is out of date w.r.t. master. My preference on this is to rebase on top of master and force push before merging, unless that has the risk of subtly breaking stuff along the way.

2020-09-22 02:22 UTC, germasch commented on include/gtensor/capi.h
> +void* gt_backend_managed_allocate(size_t nbytes);
Ok, it already has `size_t`, so great ;)

2020-09-22 02:23 UTC, germasch approved these changes

2020-09-22 03:08 UTC, merged