Pr/const refactor
wdmapp/gtensor pull request #40
Opened 2020-10-02 19:48 UTC by bd4

Closes #39 without resorting to const_cast

2020-10-03 15:06 UTC, germasch requested changes
Looks very nice, thanks!

Here's one question, which I'm not sure has been addressed: Is, e.g., a `gtensor_view<double, N>` convertible to a `gtensor_view<const double, N>`? I think I've hit something like this before (a long time ago). Can't quite remember the details, though.

2020-10-03 15:06 UTC, germasch commented on include/gtensor/span.h
> +using device_span = span<T>;
Not necessarily in this PR, but what are the differences between `span` and `device_span`? If it's just the `__host__ __device__` stuff, maybe it can be unified (e.g., made `constexpr`, which should make it work on the device)

2020-10-04 00:45 UTC, bd4 commented on include/gtensor/expression.h
> +             .to_kernel());
A pointer happened when I had a bug in gtensor_view::view, but I think you are correct it should not happen normally, I'll set it back to just remove ref

2020-10-04 00:46 UTC, bd4 commented on include/gtensor/gfunction.h
>  {
good point, it should work with just const, I'll see if the tests pass that way

2020-10-04 00:49 UTC, bd4 commented on include/gtensor/span.h
> +using device_span = span<T>;
for thrust, I think the two span types are necessary, because of the device_pointer and device_reference hackery. if those are stripped out before leaving gtensor public interfaces (which we have talked about...), then perhaps there could be one span type. but span is part of the internal interface, so have to see how that would play out

2020-10-04 00:51 UTC, bd4 commented on include/gtensor/span.h
> +using device_span = span<T>;
I added it for span but forgot gtensor_view, that should be trivial to add. gview could also support it in some cases but that is more complicated.

2020-10-05 15:40 UTC, bd4 commented on include/gtensor/gfunction.h
>  {
It does work with just const

2020-10-05 18:08 UTC, bd4 commented
Additional manual tests passing:
* github CI SYCL tests (using SYCL host device)
* unit tests and daxpy example on nVidia GPU (1070 Ti) with and without HIP
* unit tests and daxpy example on SYCL Intel GPU
* unit tests on AMD GPU with and without HIP
* no known regressions with gtensor updated in GENE compared to latest cuda branch (with thrust zero init hack)

2020-10-06 01:22 UTC, germasch approved these changes

2020-10-06 11:02 UTC, merged