Better performance for small 1D assignments and launches with CUDA
wdmapp/gtensor pull request #64
Opened 2021-02-16 18:15 UTC by td-mpcdf

If the linear size of a 1D assign or launch is less than the default blocksize BS_1D of 256, use a smaller blocksize to make it possible to have several blocks. This can increase performance a bit due to better latency hiding.

2021-02-16 18:19 UTC, germasch requested changes
Do you have a benchmark or some other motivation why this is important? Since we don't use anything like `__syncthreads()` that synchronizes inside a block, I don't quite see how multiple blocks would help, and we're talking tiny problems here in the first place.

2021-02-16 18:22 UTC, germasch commented
It'd be great if @mhrywniak had input on this ;)

2021-02-16 20:38 UTC, bd4 commented on include/gtensor/assign.h
> +      BS_1D = 32;
warp size on AMD gpus is 64, so I don't think this is portable

2021-02-17 08:30 UTC, td-mpcdf commented on include/gtensor/assign.h
> +      BS_1D = 32;
For AMD, BS_1D can be 64 for small dimension. I think there are also some other places where we differentiate between the architectures.

2021-02-17 12:57 UTC, bd4 commented on include/gtensor/assign.h
> +      BS_1D = 32;
yes we can use #defines for this, maybe something in include/gtensor/device_backend.h, GTENSOR_MIN_BLOCK_SIZE, where there are already device specific defines. Or in macros.h, if that would create a circular header dependency.

2021-02-17 12:58 UTC, bd4 commented
From a quick googling, I don't see anything about performance of small blocks. In general, it would be great if we start adding benchmarks for when we do performance optimization - at least then we know what we are optimizing for. As other apps use gtensor, there may be cases where optimizing for one app slows down another, without a further rethinking, so knowing what case we optimized for is very helpful.

2021-02-17 13:01 UTC, bd4 commented
Is there a specific case in GENE that this is trying to improve? I can take a stab at writing a benchmark case for this, but wondering what the original motivating case is.

2021-02-17 13:37 UTC, mhrywniak commented
> 
> 
> It'd be great if @mhrywniak had input on this ;)

I'm not sure of the circumstances of the launching code, but it looks like this change only takes effect when you have a launch that in total has fewer than the default 256 elements (right?). So in this case instead of launching a large block with potentially idle threads, you launch multiple smaller blocks concurrently. 

Those could go to multiple SMs (instead of the large block, which will be resident on a single SM), which might explain what Tilman is seeing. I agree some (micro)benchmark/sample launch would help.

2021-04-22 01:06 UTC, germasch commented
I guess I'm closing this due to inactivity...

2021-04-22 01:06 UTC, closed without merging