Pr/fft refactor
wdmapp/gtensor pull request #70
Opened 2021-03-11 18:51 UTC by bd4

2021-03-12 02:41 UTC, germasch requested changes
LGTM, with I'd say the only thing that should be changed for this PR being the `"cufft"` lib.

2021-03-12 02:41 UTC, germasch commented on CMakeLists.txt
> +    target_link_libraries(gtfft INTERFACE "cufft")
Whereas I don't think it hurts, there's no reason to put the name of the library in quotes. 

In any case, not sure we're requiring a new enough cmake yet, but there's a better way to find cufft now: https://cmake.org/cmake/help/git-stage/module/FindCUDAToolkit.html

2021-03-12 02:41 UTC, germasch commented on include/gtensor/fft.h
> +
Do we still need this?

2021-03-12 02:41 UTC, germasch commented on include/gtensor/fft.h
> +  }
Not sure there's an easy way to do this, but it'd be kinda nice to handle constness (both making it more explicit, and enforcing it, ie., `out` must return a pointer to a non-const type -- this may already be the case.)

2021-03-12 02:41 UTC, germasch commented on include/gtensor/fft/cuda.h
> +  using Bout = cufftDoubleComplex*;
There may be a reason, but I guess I'd find it preferable to define the type without the `*` here, for symmetry between `Tin` and `Bin`.

2021-03-12 02:41 UTC, germasch commented on include/gtensor/fft/cuda.h
> +                  typename detail::fft_config<D, R>::Tout* outdata)
So it does look like passing a const * for `indata` won't work, and while that may be a reflection of the original interface, it'd be kinda nice to do this correctly in our own interface.

2021-03-12 02:41 UTC, germasch commented on tests/test_cfft.cxx
> +  expect_complex_eq(h_B(0, 0), T(8, 0));
What's the reason again that `EXPECT_EQ()` doesn't work here?

2021-03-12 14:50 UTC, bd4 commented on CMakeLists.txt
> +    target_link_libraries(gtfft INTERFACE "cufft")
Current min version is 3.13; FindCUDAToolkit was added in 3.17. In my experience, if a system is running ancient RHEL with an old cmake, they provide a module with 3.17 or greater. So I don't think it would be too limiting to bump the minimum version to 3.17. Lets keep that as a separate PR though.

2021-03-12 14:51 UTC, bd4 commented on include/gtensor/fft.h
> +
Nope, good catch

2021-03-12 14:52 UTC, bd4 commented on include/gtensor/fft.h
> +  }
I can const cast before passing in to cuFFT. For some reason none of the low level libraries using const input. I'll try and see if it works.

2021-03-12 14:55 UTC, bd4 commented on tests/test_cfft.cxx
> +  expect_complex_eq(h_B(0, 0), T(8, 0));
It should really be called `expect_complex_near`. I think the issue was that `EXPECT_NEAR` did not work with complex.

2021-03-12 15:52 UTC, bd4 commented on tests/test_cfft.cxx
> +  expect_complex_eq(h_B(0, 0), T(8, 0));
renamed

2021-03-12 15:53 UTC, bd4 commented on include/gtensor/fft/cuda.h
> +                  typename detail::fft_config<D, R>::Tout* outdata)
added const to indata type in C++ and C interfaces

2021-03-12 15:53 UTC, bd4 commented on include/gtensor/fft/cuda.h
> +  using Bout = cufftDoubleComplex*;
good point, removed pointer

2021-03-13 00:33 UTC, germasch approved these changes

2021-03-25 03:21 UTC, bd4 commented
Design change - moved fft includes to `include/gt-fft`, to make it more clear that this is an optional add on when looking at the code (and could be separated into a different repo if we ever want/need to).

Also considering removing the CLib portion, and making that part of GENE only. Then gtensor becomes a C++ library only. The drawback is it will be a bit more work to set up testing for the CLib layer.

2021-03-28 01:23 UTC, germasch requested changes

2021-03-28 01:23 UTC, germasch commented on include/gt-fft/backend/sycl.h
> +  virtual ~FFTPlanManySYCL() { delete plan_; }
Since this class is probably not meant to be derived from, I think having this `virtual` may give the wrong impression.

In any case, I advocate using `std::unique_ptr` for the plan -- not only does it mean you don't need a destructor, it also helps to get other semantics correct (in particular, move ctor/assign should work, and copy ctor/assign will be deleted, which is preferable to what would currently happen if one tried).

2021-03-28 01:23 UTC, germasch commented on include/gt-fft/backend/cuda.h
> +
I commented on a similar issue later (sycl), though this comment may show up first. `std::unique_ptr` doesn't (easily) work here. But I think there's still the "rule of five" (IIRC), ie., if one has destructor, one should also define copy/move ctor/assign. Or, at least, delete them to prevent bad things from happening.

2021-03-28 01:24 UTC, germasch commented on include/gt-fft/backend/cuda.h
> +
I guess github actually does put comments in the order written, maybe ;) -- in any case at least in this case.

2021-03-28 01:27 UTC, bd4 commented on include/gt-fft/backend/cuda.h
> +
Seems like an FFT plan should be a move only type? I am curious now what semantics the MKL descriptor has.

2021-03-28 01:30 UTC, bd4 commented on include/gt-fft/backend/cuda.h
> +
Huh MKL declares a destructor, but no copy/move ctor/assign.

2021-03-28 01:46 UTC, bd4 commented on include/gt-fft/backend/sycl.h
> +  virtual ~FFTPlanManySYCL() { delete plan_; }
It actually is derived from, to define the backend-neutral helper methods that take gtensor container objects. But perhaps there is a better way of doing that.

2021-03-28 01:52 UTC, germasch commented on include/gt-fft/backend/sycl.h
> +  virtual ~FFTPlanManySYCL() { delete plan_; }
Ok -- well, nothing wrong about that, I guess there's a choice of inheritance vs composition, but I can see the point for inheritance here.

The `virtual` thing in the destructor probably still isn't needed, but arguably should be done anyway (besides that it's moot now due to using unique_ptr). This is about keeping a pointer to the base class, when the actual object is a derived class, so then when deleting the pointer, the "wrong" destructor gets called. That's probably not how one would use this class, but in any case, I agree that a class that is derived from should have a virtual destructor, just in case.

2021-03-28 01:54 UTC, germasch commented on include/gt-fft/backend/cuda.h
> +
That's usually a bug: https://en.cppreference.com/w/cpp/language/rule_of_three

But usually doesn't mean always, so I don't know.

2021-03-30 20:08 UTC, merged