little bits and pieces
wdmapp/gtensor pull request #72
Opened 2021-04-02 02:43 UTC by germasch

This add some `GT_INLINE` to functions that should be usable from the device (ie., which I needed to be usable on the device), and also adds `inline` to  `GT_INLINE` macro, which was missing in the CUDA case.

2021-04-02 03:05 UTC, germasch commented
@bd4 I'm kinda at a loss as to why there are so many CI failures -- I don't think they're because of the actual changes in this PR...

2021-04-02 23:12 UTC, bd4 requested changes
Host compiler failures might be because github flipped the switch on default ubuntu 20.04. I will work on a PR that fixed that.

The HIP failure I am more concerned about. I think just need GT_INLINE on the definition outside the class, as well as the declaration inside the class.

2021-04-02 23:12 UTC, bd4 commented on include/gtensor/gstrided.h
> +  GT_INLINE gstrided(const shape_type& shape, const strides_type& strides);
Do we ever really want/need to have constructors execute on device?

2021-04-03 00:14 UTC, germasch commented on include/gtensor/gstrided.h
> +  GT_INLINE gstrided(const shape_type& shape, const strides_type& strides);
Yes, I think that's sometimes useful (I think I hit that case). For example, if one wants to take a slice and then uses that subsequently. It's of course not free, but relatively cheap to do that, even in device code.

On the other hand, I don't think we want to do anything on the device that involves dynamic memory allocation.

You're right, though that there's an issue in where to put `GT_INLINE`, and what it means. It doesn't actually make sense to "inline" something that's a declaration only -- but it does need the `__host__ __device__` there. I guess at as long as the compiler doesn't complain about the superfluous `inline` it doesn't hurt to have this all in one macro. But yeah, need to look at adding it to the definition, too.

2021-04-03 00:41 UTC, bd4 commented on include/gtensor/gstrided.h
> +  GT_INLINE gstrided(const shape_type& shape, const strides_type& strides);
Unfortunately the ROCM/HIP stack is more picky here. We'll see what happens after rebasing on the CI fix, but I think the HIP failure is real.

2021-04-03 13:13 UTC, germasch commented on include/gtensor/gstrided.h
> +  GT_INLINE gstrided(const shape_type& shape, const strides_type& strides);
Took me more attempts than it should have, but got it right finally...

2021-04-03 16:37 UTC, bd4 approved these changes

2021-04-04 00:28 UTC, bd4 commented
LGTM

2021-04-05 13:40 UTC, germasch commented
I realize it isn't good style to add stuff after the fact, but I did anyway :(

I added launch support on host for 4, 5, 6-d calculations, and also made the `gtensor_span` ctor usable from the device. Ie., this should be fairly safe, and the CI really has been good at noticing problems that I missed...

2021-04-05 13:42 UTC, germasch commented
Also, I think I added `GT_INLINE` to `sarray::operator==` etc, and I don't think that was actually working since it uses `std::equal`, which isn't defined on the device (which is kinda annoying). Primarily this means I should have added tests to make sure that stuff really works..

It did cause warnings, which is how I noticed it. I wonder whether we should try to get this warnings-clean and do the CI with `-Werror` (if that even works with nvcc)...

2021-04-05 16:56 UTC, merged